name: Switch Build

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64]
        mode: [debug, release]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    container: devkitpro/devkita64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc

    # Force xmake to a specific folder (for cache)
    - name: Set xmake env
      run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
    
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update --root

    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --toolchain=devkita64 -p cross --yes --root -vD

    - name: Build Switchseerr
      run: xmake --yes --root
    
    - uses: actions/upload-artifact@v4
      with:
        name: Switchseerr-${{ matrix.arch }}-${{ matrix.mode }}
        path: build/cross/aarch64/${{ matrix.mode }}/SimpleModDownloader.nro

