name: Windows Build

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [debug, release]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@dev
      
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes

    - name: Build Switchseerr
      run: xmake --yes

    - name: Install Switchseerr
      run: xmake install -o out

    - name: "Set PACKAGE_NAME variable"
      run: echo "PACKAGE_NAME=windows_${{ matrix.arch }}_${{ matrix.mode }}.zip" >> $GITHUB_ENV
      shell: bash

    - name: Archive result
      uses: ihiroky/archive-action@v1
      with:
        root_dir: out
        file_path: ${{ env.PACKAGE_NAME }}
        verbose: true
    
    - uses: actions/upload-artifact@v4
      with:
        name: Switchseerr-${{ matrix.arch }}-${{ matrix.mode }}
        path: ${{ env.PACKAGE_NAME }}

